In [1]:
!python --version

Python 3.14.0

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('Job_1_resource_world_population.csv')

In [4]:
df.head()

,Rank,CCA3,Country/Territory,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771,38972230,33753499,28189672,19542982,10694796,12486631,10752971,652230,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321,2866849,2882481,2913399,3182021,3295066,2941651,2324731,28748,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225,43451666,39543154,35856344,30774621,25518074,18739378,13795915,2381741,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273,46189,51368,54849,58230,47818,32886,27075,199,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824,77700,71746,71519,66097,53569,35611,19860,468,170.5641,1.0100,0.00

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022 Population              234 non-null    int64
 6   2020 Population              234 non-null    int64
 7   2015 Population              234 non-null    int64
 8   2010 Population              234 non-null    int64
 9   2000 Population              234 non-null    int64
 10  1990 Population              234 non-null    int64
 11  1980 Population              234 non-null    int64
 12  1970 Population              234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 31.2+ KB

In [6]:
df.shape

(234, 17)

In [7]:
df.isnull().sum()

Rank                           0
CCA3                           0
Country/Territory              0
Capital                        0
Continent                      0
2022 Population                0
2020 Population                0
2015 Population                0
2010 Population                0
2000 Population                0
1990 Population                0
1980 Population                0
1970 Population                0
Area (km²)                     0
Density (per km²)              0
Growth Rate                    0
World Population Percentage    0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

,Rank,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
count,234.000000,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,2.340000e+02,234.000000,234.000000,234.000000
mean,117.500000,3.407441e+07,3.350107e+07,3.172996e+07,2.984524e+07,2.626947e+07,2.271022e+07,1.898462e+07,1.578691e+07,5.814494e+05,452.127044,1.009577,0.427051
std,67.694165,1.367664e+08,1.355899e+08,1.304050e+08,1.242185e+08,1.116982e+08,9.783217e+07,8.178519e+07,6.779509e+07,1.761841e+06,2066.121904,0.013385,1.714977
min,1.000000,5.100000e+02,5.200000e+02,5.640000e+02,5.960000e+02,6.510000e+02,7.000000e+02,7.330000e+02,7.520000e+02,1.000000e+00,0.026100,0.912000,0.000000
25%,59.250000,4.197385e+05,4.152845e+05,4.046760e+05,3.931490e+05,3.272420e+05,2.641158e+05,2.296142e+05,1.559970e+05,2.650000e+03,38.417875,1.001775,0.010000
50%,117.500000,5.559944e+06,5.493074e+06,5.307400e+06,4.942770e+06,4.292907e+06,3.825410e+06,3.141146e+06,2.604830e+06,8.119950e+04,95.346750,1.007900,0.070000
75%,175.750000,2.247650e+07,2.144798e+07,1.973085e+07,1.915957e+07,1.576230e+07,1.186923e+07,9.826054e+06,8.817329e+06,4.304258e+05,238.933250,1.016950,0.280000
max,234.000000,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,9.823725e+08,8.225344e+08,1.709824e+07,23172.266700,1.069100,17.880000

In [10]:
population_columns = [
    '1970 Population', '1980 Population', '1990 Population',
    '2000 Population', '2010 Population', '2015 Population',
    '2020 Population', '2022 Population'
]

continent_population_stats = df.groupby('Continent')[population_columns].agg(
    ['mean', 'median', 'var', 'std']
)

print("Population Statistics by Continent:")
print(continent_population_stats)

Population Statistics by Continent:
              1970 Population                                         \
                         mean     median           var           std
Continent
Africa           6.411304e+06  3667394.0  9.403635e+13  9.697234e+06
Asia             4.289813e+07  6212695.0  1.913911e+16  1.383442e+08
Europe           1.311848e+07  4184092.0  5.902318e+14  2.429469e+07
North America    7.885865e+06   135645.0  1.046863e+15  3.235526e+07
Oceania          8.469683e+05    58989.0  7.122413e+12  2.668785e+06
South America    1.378194e+07  5378954.0  6.243199e+14  2.498639e+07

              1980 Population                                         \
                         mean     median           var           std
Continent
Africa           8.448007e+06  4408230.0  1.590864e+14  1.261294e+07
Asia             5.270668e+07  7641007.0  2.809997e+16  1.676305e+08
Europe           1.385054e+07  4439982.0  6.481203e+14  2.545821e+07
North America    9.207334e+06   150992.0  1.329926e+15  3.646815e+07
Oceania          9.965322e+05    76299.0  9.707899e+12  3.115750e+06
South America    1.727064e+07  6935966.5  1.002779e+15  3.166669e+07

              1990 Population             ... 2015 Population                \
                         mean     median  ...             var           std
Continent                                 ...
Africa           1.119563e+07  5827069.0  ...    1.000210e+15  3.162610e+07
Asia             6.421127e+07  9802802.0  ...    7.143726e+16  2.672775e+08
Europe           1.440642e+07  4684008.5  ...    7.386151e+14  2.717747e+07
North America    1.053166e+07   169017.5  ...    2.917475e+15  5.401366e+07
Oceania          1.162775e+06    98603.0  ...    2.702072e+13  5.198146e+06
South America    2.122474e+07  8773015.5  ...    2.817911e+15  5.308400e+07

              2020 Population                                          \
                         mean      median           var           std
Continent
Africa           2.387144e+07  12643123.0  1.283621e+15  3.582766e+07
Asia             9.326173e+07  17688051.5  7.702702e+16  2.775374e+08
Europe           1.491584e+07   5162979.0  7.506258e+14  2.739755e+07
North America    1.485591e+07    234990.5  3.135190e+15  5.599277e+07
Oceania          1.910149e+06    112106.0  3.170090e+13  5.630356e+06
South America    3.082357e+07  14762378.5  3.044265e+15  5.517486e+07

              2022 Population
                         mean      median           var           std
Continent
Africa           2.503037e+07  13352864.0  1.411678e+15  3.757230e+07
Asia             9.442767e+07  18082920.0  7.824368e+16  2.797207e+08
Europe           1.486295e+07   5228714.0  7.433757e+14  2.726492e+07
North America    1.500740e+07    236399.0  3.182998e+15  5.641806e+07
Oceania          1.958198e+06    114164.0  3.311927e+13  5.754935e+06
South America    3.120119e+07  15112555.0  3.105366e+15  5.572581e+07

[6 rows x 32 columns]

In [12]:
df.shape

(234, 17)

In [11]:

cumulative_growth_df = df[['Country/Territory', '1970 Population']].copy()
cumulative_growth_df

     Country/Territory  1970 Population
0          Afghanistan         10752971
1              Albania          2324731
2              Algeria         13795915
3       American Samoa            27075
4              Andorra            19860
..                 ...              ...
229  Wallis and Futuna             9377
230     Western Sahara            76371
231              Yemen          6843607
232             Zambia          4281671
233           Zimbabwe          5202918

[234 rows x 2 columns]

In [13]:
for col in population_columns[1:]:
    cumulative_growth_df[f'{col} Cumulative Growth (%)'] = (
        (df[col] - df['1970 Population']) / df['1970 Population']
    ) * 100

print("Cumulative Population Growth for Each Country (relative to 1970 Population):")
print(cumulative_growth_df.head())

Cumulative Population Growth for Each Country (relative to 1970 Population):
  Country/Territory  1970 Population  1980 Population Cumulative Growth (%)  \
0       Afghanistan         10752971                              16.122614
1           Albania          2324731                              26.537264
2           Algeria         13795915                              35.832803
3    American Samoa            27075                              21.462604
4           Andorra            19860                              79.310171

   1990 Population Cumulative Growth (%)  \
0                              -0.541013
1                              41.739668
2                              84.968333
3                              76.613112
4                             169.733132

   2000 Population Cumulative Growth (%)  \
0                              81.744952
1                              36.876955
2                             123.070532
3                             115.069252
4                             232.814703

   2010 Population Cumulative Growth (%)  \
0                             162.157054
1                              25.321983
2                             159.905516
3                             102.581717
4                             260.115811

   2015 Population Cumulative Growth (%)  \
0                             213.899284
1                              23.992023
2                             186.629441
3                              89.724838
4                             261.258812

   2020 Population Cumulative Growth (%)  \
0                             262.432206
1                              23.319601
2                             214.960378
3                              70.596491
4                             291.238671

   2022 Population Cumulative Growth (%)
0                             282.487510
1                              22.264511
2                             225.482036
3                              63.519852
4                             301.933535

In [14]:
new_columns = []
for col in df.columns:
    if ' Population' in col and col.replace(' Population', '').isdigit() and len(col.replace(' Population', '')) == 4:
        new_columns.append(col.replace(' Population', ''))
    else:
        new_columns.append(col)

df.columns = new_columns

print("DataFrame columns after renaming:")
print(df.head())

DataFrame columns after renaming:
   Rank CCA3 Country/Territory           Capital Continent      2022  \
0    36  AFG       Afghanistan             Kabul      Asia  41128771
1   138  ALB           Albania            Tirana    Europe   2842321
2    34  DZA           Algeria           Algiers    Africa  44903225
3   213  ASM    American Samoa         Pago Pago   Oceania     44273
4   203  AND           Andorra  Andorra la Vella    Europe     79824

       2020      2015      2010      2000      1990      1980      1970  \
0  38972230  33753499  28189672  19542982  10694796  12486631  10752971
1   2866849   2882481   2913399   3182021   3295066   2941651   2324731
2  43451666  39543154  35856344  30774621  25518074  18739378  13795915
3     46189     51368     54849     58230     47818     32886     27075
4     77700     71746     71519     66097     53569     35611     19860

   Area (km²)  Density (per km²)  Growth Rate  World Population Percentage
0      652230            63.0587       1.0257                         0.52
1       28748            98.8702       0.9957                         0.04
2     2381741            18.8531       1.0164                         0.56
3         199           222.4774       0.9831                         0.00
4         468           170.5641       1.0100                         0.00

In [15]:
df.shape

(234, 17)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 234 entries, 0 to 233
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Rank                         234 non-null    int64
 1   CCA3                         234 non-null    object
 2   Country/Territory            234 non-null    object
 3   Capital                      234 non-null    object
 4   Continent                    234 non-null    object
 5   2022                         234 non-null    int64
 6   2020                         234 non-null    int64
 7   2015                         234 non-null    int64
 8   2010                         234 non-null    int64
 9   2000                         234 non-null    int64
 10  1990                         234 non-null    int64
 11  1980                         234 non-null    int64
 12  1970                         234 non-null    int64
 13  Area (km²)                   234 non-null    int64
 14  Density (per km²)            234 non-null    float64
 15  Growth Rate                  234 non-null    float64
 16  World Population Percentage  234 non-null    float64
dtypes: float64(3), int64(10), object(4)
memory usage: 31.2+ KB

In [17]:
df.to_csv('processed_data.csv', index=False)
print("Dataset successfully saved to 'processed_data.csv'")

Dataset successfully saved to 'processed_data.csv'